"""is boss

Revision ID: 181dc4fb9617
Revises: 578e88d8953d
Create Date: 2024-06-14 12:46:33.640469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181dc4fb9617'
down_revision = '578e88d8953d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isBoss', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('isBoss')

    # ### end Alembic commands ###
